///===- TVMInstMappingInfoEmitter.cpp - Generate an instruction selector --===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// TVMInstMappingInfoEmitter generates for each TVM Instruction a mapping
// between its register form (REG-form) and its stack form (S-form). More
// details about these forms could be found in TVMInstrFormats.td in TVM
// backend.
// This mapping is needed to rewrite REG-form, pseudo instruction generated by
// DAG to DAG ISel, with S-form which is the actual instruction used by the
// virtual machine.
//
//===----------------------------------------------------------------------===//

#include "CodeGenDAGPatterns.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/TableGenBackend.h"

using namespace llvm;

namespace {

class TVMInstMappingInfoEmitter {
  CodeGenDAGPatterns CDP;

public:
  TVMInstMappingInfoEmitter(RecordKeeper &R) : CDP(R) {}

  // run - Output the instruction set description.
  void run(raw_ostream &OS);

private:
};

} // End anonymous namespace

//===----------------------------------------------------------------------===//
// Main Output.
//===----------------------------------------------------------------------===//

// run - Emit the main instruction description records for the target...
void TVMInstMappingInfoEmitter::run(raw_ostream &OS) {
  emitSourceFileHeader("Target Instruction Enum Values and Descriptors", OS);

  OS << "namespace llvm {\n\n";
  OS << "namespace TVM {\n\n";

  CodeGenTarget &Target = CDP.getTargetInfo();

  ArrayRef<const CodeGenInstruction*> NumberedInstructions =
    Target.getInstructionsByEnumValue();

  unsigned Num = 0;
  std::map<std::string, int> OpcodesMap;
  for (const CodeGenInstruction *Inst : NumberedInstructions) {
    const Record* rec = Inst->TheDef;
    if (rec->isSubClassOf("NI"))
      if (rec->getValueAsBit("isStackForm"))
        OpcodesMap[rec->getName()] = Num;
    Num++;
  }

  OS << "int RForm2SForm[] = {\n";

  Num = 0;
  for (const CodeGenInstruction *Inst : NumberedInstructions) {
    std::string name = Inst->TheDef->getName();
    int idx = -1;
    auto it = OpcodesMap.find(name + "_S");
    if (it != OpcodesMap.end())
      idx = it->second;
    OS << "  " << idx << ", // " << Num << " " << name << "\n";
    Num++;
  }

  OS << "};\n\n";

  OS << "} // end namespace TVM\n\n";
  OS << "} // end namespace llvm\n\n";
}

namespace llvm {

void EmitTVMInstMappingInfo(RecordKeeper &RK, raw_ostream &OS) {
  TVMInstMappingInfoEmitter(RK).run(OS);
}

} // End llvm namespace
